/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Compensator } from "./Compensator";
export type { CompensatorFactory } from "./CompensatorFactory";
