/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as mocks from "./mocks";
export { Compensator__factory } from "./Compensator__factory";
export { CompensatorFactory__factory } from "./CompensatorFactory__factory";
export { IComp__factory } from "./IComp__factory";
export { ICompensator__factory } from "./ICompensator__factory";
export { IGovernor__factory } from "./IGovernor__factory";
