/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { Compensator } from "./Compensator";
export type { CompensatorFactory } from "./CompensatorFactory";
export type { IComp } from "./IComp";
export type { ICompensator } from "./ICompensator";
export type { IGovernor } from "./IGovernor";
